version: '3.8'

services:
  php:
    container_name: quaiAntiqueRestaurant-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/symfony
    environment:
      - APP_ENV=dev
    depends_on:
      - mysql
      - mongodb
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: quaiAntiqueRestaurant-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: quaiAntiqueRestaurant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SSL_MODE: DISABLED 
    ports:
      - "3306:3306"
    volumes:
      - quaiAntiqueRestaurant_data:/var/lib/mysql
    networks:
      - app-network

  mongodb:
    image: mongo:7
    container_name: quaiAntiqueRestaurant-mongodb
    ports:
      - "27017:27017"
    volumes:
      - quaiAntiqueRestaurant_mongo_data:/data/db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quaiAntiqueRestaurant-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: quaiAntiqueRestaurant-mongo-express
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_EXPRESS_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  quaiAntiqueRestaurant_data:
  quaiAntiqueRestaurant_mongo_data:

networks:
  app-network:
    driver: bridge
